### ISSUE TITLE
Not having a behaviour

### ISSUE THREAD

**Issue by tdesvenain** [collective/collective.dexteritytextindexer#10]
Hi,

I may be wrong,
but I think that this product is very good but could be more simple.

Now we have to activate a behaviour AND a property on fields. It is too much complex for users.

Why not 
- registering  dynamic_searchable_text_indexer on all dexterity contents 
- having base dexteritytextindexer behaviour as a IDynamicTextIndexExtender
- fallback on common SearchableText computing if there is no value generated from any dynamic text indexer

AFAIK, it won't cost a lot as mergedTaggedValueList(schemata, SEARCHABLE_KEY) is not an expensive method

**Comment by mauritsvanrees** [comment]
It is in core as behavior now.
