### ISSUE TITLE
c.dexteritytextindexer does not get triggered when running scripts

### ISSUE THREAD

**Issue by gforcada** [collective/collective.dexteritytextindexer#12]
While attempting to run [this script](https://github.com/derFreitag/plone.app.upgrade/blob/restart-proof-update/plone/app/upgrade/v43/article_case_normalizer.py) via ``./bin/instance run path/to/script/script.py Plone admin`` I see that objects are reindexed, but do not contain anything coming from collective.dexteritytextindexer.

Exactly the same script but changed to be a regular upgrade step works perfectly.

Is that a limitation of ``./bin/instance run`` way of working or is something that needs to be fixed here?

Mostly I log the issue here so that anyone stumbling upon the same problem (hopefully) finds here a solution.

**Comment by davisagli** [comment]
collective.dexteritytextindexer probably needs the plone site's component registry activated in order to work. You can do that by running `bin/instance run -Ozodb/path/to/Plone script.py`
