### ISSUE TITLE
PLIP this for Plone core?

### ISSUE THREAD

**Issue by jensens** [collective/collective.dexteritytextindexer#22]
In my opinion, all functionality of ``collective.dexteritytextindexer`` is something Plone has to offer OOTB. 

to do so:

- all significant commiters of this package need to agree and have (afaik) the Plone CLA signed.
- create a PLIP and go through PLIP process
- move code over to matching core packages plip-branches
- probably it is a good idea to create a new BBB major release here with just deprecation imports from core.

What do you think?

**Comment by jone** [comment]
👍 I agree and support that!
I have signed the CLA.
It would be great to keep `collective.dexteritytextindexer` for Plone 4 installations.

**Comment by lukasgraf** [comment]
👍 I agree as well

**Comment by gforcada** [comment]
The full committers list is ( ``git log --all --format='%cN <%cE>' | sort -u``):

Already plone contributors (although double check):
```
Asko Soukka <asko.soukka _AT_ iki.fi>
Eric BREHAULT <ebrehault _AT_ gmail.com>
Gil Forcada Codinachs <gil.forcada _AT_ freitag.de>
Gil Forcada <gforcada _AT_ gnome.org>
Jonas Baumann <jone _AT_ jone.ch>
Jonas Baumann <tschouns _AT_ gmail.com>
Lukas Graf <lukas.graf _AT_ 4teamwork.ch>
Nejc Zupan <nejc.zupan _AT_ gmail.com>
Philippe Gross <p.gross _AT_ 4teamwork.ch>
philippe.gross <philippe.gross _AT_ 4teamwork.ch>
Tom Gross <itconsense _AT_ gmail.com>
Sune Broendum Woeller <sune _AT_ woeller.dk>
```

Contributors not in plone github organization (so no CLA):
```
Izhar Firdaus <izhar _AT_ inigo-tech.com>
127001 <localhost _AT_ gmail.com>
```

@kagesenshi would you mind either signing [Plone's CLA](http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html) or at least give permission to move the code around?

@127001 only made this change https://github.com/collective/collective.dexteritytextindexer/commit/c761af346797eb5b1fb6150510ede7ed021b1fc9 but it would still be nice to get his approval.

**Comment by phgross** [comment]
👍 I agree as well.

**Comment by davisagli** [comment]
12700 <localhost _AT_ gmail.com> does not look like real contact info.

**Comment by jensens** [comment]
I think the commit by @127001 is not significant. I doubt the Plone release manager is able to decide this for commits of 1-3 lines.

**Comment by mauritsvanrees** [comment]
It is in core Plone 6.0.0a4.
