### ISSUE TITLE
Not indexing rich text fields

### ISSUE THREAD

**Issue by smcmahon** [collective/collective.dexteritytextindexer#23]
In Plone 4.3.14, I'm getting the "do you want raw or output" rendering for rich text fields.

**Comment by jensens** [comment]
merged

**Comment by mauritsvanrees** [comment]
I was just looking into fixing this when I found that @smcmahon already did it. :-) Thank you.

Note that this might need a minor change once a decision has been made about whether to take the raw or the output value, and which mimetype, in plone.app.contenttypes. See https://github.com/plone/Products.CMFPlone/issues/2066
But at the moment the code works fine.
