### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by mbaechtold** [collective/collective.dexteritytextindexer#28]
We're particularly interested in https://github.com/collective/collective.dexteritytextindexer/pull/24.

Any objections to cut a release, @mauritsvanrees, @smcmahon, @jensens?

**Comment by mauritsvanrees** [comment]
Fine with me to create a release. (I cannot do this.)
Would be nice to get pull request #27 in as well, but that can also be done later.

**Comment by jone** [comment]
`2.2.0` is out and includes #27.
