### ISSUE TITLE
When will it release support Py3?

### ISSUE THREAD

**Issue by terapyon** [collective/collective.dexteritytextindexer#36]
I want to use on Python 3 (Plone5.2). When will it make a new release?
Does it have blocker?

**Comment by ale-rt** [comment]
Current master is working since a while in Python3 in production, it would just need a release.
CC @jone @maethu @lukasgraf @buchi (as possible releasers)

**Comment by lukasgraf** [comment]
@terapyon @ale-rt I released [`collective.dexterityindexer = 2.4.0`](https://pypi.org/project/collective.dexteritytextindexer/2.4.0/)

**Comment by ale-rt** [comment]
Thanks!
