### ISSUE TITLE
Avoid duplicate values (?)

### ISSUE THREAD

**Issue by laulaz** [collective/collective.dexteritytextindexer#38]
When you add new values to `SearchableText` index (via `IDynamicTextIndexExtender`), you can end up with duplicate values in the index.

Couldn't we add some code to remove duplicates ?  or is there a reason why we keep them in the first place ?  (this also occurs in `plone.app.contenttypes` indexers)

Thanks for your advices

**Comment by gbastien** [comment]
Hi @laulaz 

we get the same problem here, I see where it is happening, actually when calling ```mergedTaggedValueList(schemata, SEARCHABLE_KEY)``` in ```indexer.py``` we pass a generated_interface, and mergedTaggedValueList when looking in __iro__ will add fields from the generated interface and from the base interface as well.

I think checking for field duplicate in indexer.get_searchable_contexts_and_fields should be enough, I will try to propose a fix and a test...

Gauthier

**Comment by gbastien** [comment]
This is probably fixed with #44 @laulaz can you check?
I checked locally this seems correct now.
See you!
Gauthier

**Comment by laulaz** [comment]
👍
