### ISSUE TITLE
New release for Py3?

### ISSUE THREAD

**Issue by agitator** [collective/collective.dexteritytextindexer#39]
@pbauer @staeff do you think dexterityindexer is ready for a new relase?

**Comment by agitator** [comment]
according to @pbauer nothing missing for a release

@buchi @jone @lukasgraf could one of you make it happen? ;-)

**Comment by lukasgraf** [comment]
Will do 👍

**Comment by lukasgraf** [comment]
@agitator released as [`collective.dexteritytextindexer = 2.3.0`](https://pypi.org/project/collective.dexteritytextindexer/2.3.0/) 🎉

**Comment by agitator** [comment]
Thx!
