### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.dexteritytextindexer#45]
Is it possible to make a new package release ? or give me the right on Pypi (user : laz) to do so ?
@jone or @lukasgraf maybe ?

Thank you very much !  🙏

**Comment by laulaz** [comment]
As `collective.dexteritytextindexer` will be merged into Plone core (https://github.com/plone/Products.CMFPlone/issues/2780), it would be great to have a "last" release.

Could you please release the package or give me the rights to do it on Pypi (user: laz) ?

@4teamwork, @bierik, @buchi, @deif, @elioschmutz, @2e12, @jone, @lukasg, @maethu, @njohner, @phgross, @tinagerber

Thank you !  🙏

**Comment by maethu** [comment]
@laulaz I just released the version 2.4.1 on pypi 😊
