### ISSUE TITLE
Can I mark NamedBlobFile field as searchableText?

### ISSUE THREAD

**Issue by FarooqAlaulddin** [collective/collective.dexteritytextindexer#46]
I am trying to use collective.dexteritytextindexer to mark few fields searchable (Add them to SearchableText). I want them to be pushed to solr using collective.solr. The issue is that I am not able to index to solr any NamedBlobFile field type.

    from collective import dexteritytextindexer
    from plone.autoform.interfaces import IFormFieldProvider
    from plone.supermodel.model import Schema
    from zope import schema
    from zope.interface import alsoProvides
    
    class IMyBehavior(Schema):
  
        dexteritytextindexer.searchable('title', 'file')
        title = schema.Text(title=u'title')
        description = schema.Text(title=u'description')

         file = NamedBlobFile(
	       title=_(u"File"),
	       description=_(u"document associated with this object"),
               required = False,
         )
         

- This example will only index title but not the file text. The file is text only pdf.
- Solr schema has the searchableText field.
- Am I missing something?

_Plone 5.2.8
Solr 8.11.2
Collective solr 8.4.2_

**Comment by gforcada** [comment]
Without solr on the equation, does your text files get indexed in plain zope catalog? Once that works, so it should on solr via collective.solr.

**Comment by FarooqAlaulddin** [comment]
PDF files were not being indexed due to the fact that collective.solr did not know what to do with it. 
I forgot to define name & class to handle such content-type at https://github.com/collective/collective.solr/blob/main/src/collective/solr/configure.zcml


    <adapter
    factory=".indexer.DXFileBinaryAdder"
    for="plone.dexterity.interfaces.IDexterityContent"
    name="File"
    />

File is the name of the field in your content-type.
